export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';

export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

export const FETCH_MORE_PRODUCTS_REQUEST = 'FETCH_MORE_PRODUCTS_REQUEST';
export const FETCH_MORE_PRODUCTS_SUCCESS = 'FETCH_MORE_PRODUCTS_SUCCESS';
export const FETCH_MORE_PRODUCTS_FAILURE = 'FETCH_MORE_PRODUCTS_FAILURE';
export const SET_NO_MORE = 'SET_NO_MORE';

export const FETCH_SALES_REQUEST = 'FETCH_SALES_REQUEST';
export const FETCH_SALES_SUCCESS = 'FETCH_SALES_SUCCESS';
export const FETCH_SALES_FAILURE = 'FETCH_SALES_FAILURE';

export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

export const SEND_ORDER_REQUEST = 'SEND_ORDER_REQUEST';
export const SEND_ORDER_SUCCESS = 'SEND_ORDER_SUCCESS';
export const SEND_ORDER_FAILURE = 'SEND_ORDER_FAILURE';

export const CHANGE_ORDER_DETAILS = 'CHANGE_ORDER_DETAILS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const OPEN_SEARCH = 'OPEN_SEARCH';
export const CLOSE_SEARCH = 'CLOSE_SEARCH';
export const START_SEARCH = 'START_SEARCH';

export const CHANGE_COUNTER = 'CHANGE_COUNTER';
export const SELECT_SIZE = 'SELECT_SIZE';