export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';

export const CATALOG_INIT = 'CATALOG_INIT'; 
export const CATALOG_FETCH_SUCCESS = 'CATALOG_FETCH_SUCCESS';
export const CATALOG_FETCH_FAILURE = 'CATALOG_FETCH_FAILURE';
export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

export const FETCH_SALES_REQUEST = 'FETCH_SALES_REQUEST';
export const FETCH_SALES_SUCCESS = 'FETCH_SALES_SUCCESS';
export const FETCH_SALES_FAILURE = 'FETCH_SALES_FAILURE';

export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

export const SEND_ORDER_REQUEST = 'SEND_ORDER_REQUEST';
export const SEND_ORDER_SUCCESS = 'SEND_ORDER_SUCCESS';
export const SEND_ORDER_FAILURE = 'SEND_ORDER_FAILURE';
export const SEND_ORDER = 'SEND_ORDER';
export const CART_SEND_INIT = 'CART_SEND_INIT';
export const CART_SEND_REQUEST = 'CART_SEND_REQUEST';

export const CHANGE_ORDER_DETAILS = 'CHANGE_ORDER_DETAILS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const CATALOG_SEARCH_CHANGE = 'CATALOG_SEARCH_CHANGE';

export const CHANGE_COUNTER = 'CHANGE_COUNTER';
export const SELECT_SIZE = 'SELECT_SIZE';

export const STORAGE_CART_ORDERS = 'STORAGE_CART_ORDERS';